### ISSUE TITLE
Jekyll-Style Blogging On Rails

### ISSUE THREAD

**Issue by metaskills** [nz/jekyll-rails-hybrid#2]
Do you want to use your existing Rails' layouts & business logic for your new Blog? Do you know and love Jekyll, but cant seem to get the two to play nice together?

https://homemarks.com/blog/2014-04-19-jekyll-style-blogging-on-rails

Hey Nick! Thought you might be interested in this. Kind of spam, :meat_on_bone: :email:, maybe. Maybe even worth a note on the README since this repo is a top hit for jekyll and rails? Cheers!

**Comment by nz** [comment]
Dig it! Added a link in the readme in 6969afd3ff74ce1c9cd55eb5e67aa133245a805b.

I'd _love_ a PR for a branch that demonstrates your ideas. I could see turning this repo into a collection of various example branches that tackle Jekyll-Rails integration.

Alternately, you'd think there could be a decent way to package up a gem that did something similar…

**Comment by metaskills** [comment]
:heart: THANKS!
